# Generated by Django 5.0.3 on 2024-03-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordered_item_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_item',
            name='total_price',
        ),
    ]
