# Generated by Django 5.0.3 on 2024-03-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_ordered_item_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_item',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
